name: Integration Tests

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  workflow_dispatch:
  pull_request:
    branches:
      [ main, develop ]

permissions:
  contents: read

jobs:
  build-jar:
    runs-on: ubuntu-latest
    name: Build JAR and Upload Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Prepare Artifacts
        run: |
          mkdir -p artifacts/osx artifacts/windows artifacts/linux
          cp cli/target/buildcli.jar artifacts/osx/
          cp cli/target/buildcli.jar artifacts/windows/
          cp cli/target/buildcli.jar artifacts/linux/
          cp scripts/osx/buildcli artifacts/osx/
          cp scripts/windows/buildcli.bat artifacts/windows/
          cp scripts/linux/buildcli artifacts/linux/

      - name: Upload Artifacts
        uses:  actions/upload-artifact@v4
        with:
          name: buildcli-artifacts
          path: artifacts/

  integration-tests:
    needs: build-jar
    strategy:
      matrix:
        java: [ 21 ]
        java-distribution: [ temurin ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    name: Test BuildCLI (Java ${{ matrix.java }} ${{ matrix.java-distribution }} - ${{ matrix.os }})
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java-distribution }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: buildcli-artifacts
          path: artifacts/

      - name: Verify BuildCLI installation on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          chmod +x artifacts/linux/buildcli
          if ! ./artifacts/linux/buildcli version; then
            echo "BuildCLI command not found or failed to execute."
            exit 1
          fi

      - name: Verify BuildCLI installation on macOS
        if: matrix.os == 'macos-latest'
        run: |
          chmod +x artifacts/osx/buildcli
          if ! ./artifacts/osx/buildcli version; then
            echo "BuildCLI command not found or failed to execute."
            exit 1
          fi

      - name: Verify BuildCLI installation on Windows
        if: matrix.os == 'windows-latest'
        run: |
          if (-not (artifacts\windows\buildcli.bat version)) {
            Write-Error "BuildCLI command not found or failed to execute."
            exit 1
          }