name: Release Build and Upload

on:
  release:
    types: [published]

permissions:
  contents: write


jobs:
  build-jar:
    runs-on: ubuntu-latest
    name: Build JAR and Upload Artifact
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests
      - name: Prepare Artifacts
        run: |
          mkdir -p artifacts/osx artifacts/windows artifacts/linux
          ln cli/target/buildcli.jar artifacts/linux/
          ln cli/target/buildcli.jar artifacts/osx/
          ln cli/target/buildcli.jar artifacts/windows/
          cp -r scripts/* artifacts/

      - name: Compress Artifacts
        run: |
          zip -r artifacts/linux.zip artifacts/linux/
          zip -r artifacts/osx.zip artifacts/osx/
          zip -r artifacts/windows.zip artifacts/windows/
          tar -czvf artifacts/linux.tar.gz -C artifacts linux/
          tar -czvf artifacts/osx.tar.gz -C artifacts osx/
          tar -czvf artifacts/windows.tar.gz -C artifacts windows/

      - name: Upload Artifacts
        run: gh release upload ${{ github.event.release.tag_name }} artifacts/linux.zip artifacts/osx.zip artifacts/windows.zip artifacts/linux.tar.gz artifacts/osx.tar.gz artifacts/windows.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}